### ISSUE TITLE
Mouseenter and Mouseleave events doesn't bubble.

### ISSUE THREAD

**Issue by fernandosouza** [metal/crystal-tooltip#1]
There are events delegated to the DOM document listening these events but they doesn't bubble to parent elements. See syncTriggerEvents method from Tooltip class.

**Comment by eduardolundgren** [comment]
The mouseover event fires when the user moves the mouse onto an element. The mouseout event fires when the user moves the mouse out of an element. And they bubbles.

`mouseover` Fires when the user moves the mouse over the element you registered the event on or one of its descendants.
`mouseout` Fires when the user moves the mouse out of the element you registered the event on or one of its descendants.
`mouseenter and mouseleave` Similar to mouseover and mouseout, but these events do not bubble.

I don't recall anywhere that mouseenter/mouseleave events bubbles, are we missing something?

**Comment by fernandosouza** [comment]
So... As the mouseenter event and mouseleave event doesn't bubble up through the DOM hierarchy these events never will hit the document. These events are used as default to show and hide the tooltip and as soon as I opened the demo it didn't work. To get it working I needed to use the dom.on() method instead dom.delegate() method.

See:

triggerEvents[0] //mouseenter
triggerEvents[1] //mouseleave 
selector //button

this.eventHandler_.add(
    dom.delegate(document, triggerEvents[0], selector, this.handleShow.bind(this)),
    dom.delegate(document, triggerEvents[1], selector, this.handleHide.bind(this)));

**Comment by eduardolundgren** [comment]
The polyfill is supposed towork with delegate, https://github.com/metal/metal.js/blob/master/src/dom/events.js#L14.

That may need some investigation. /cc @mairatma

**Comment by mairatma** [comment]
Thanks for catching this @fernandosouza!

This was a regression because of a change we made in metal. Now components need to explicitly import the custom events module to get them working properly, and this component wasn't doing that yet. I've fixed it already: https://github.com/metal/crystal-tooltip/commit/2545654fc608ead8c433d20d2fe342aeb1f74477.

**Comment by fernandosouza** [comment]
You're welcome. Thank you.

**Comment by eduardolundgren** [comment]
Thank you.,
